[package]
edition = "2018"
name = "tangram_app_training_stats_index_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
futures = "0.3"
html = { path = "../../../../../../../../../html" }
http = "0.2"
hyper = { version = "0.14", features = ["server"] }
num = "0.4"
tangram_app_common = { path = "../../../../../../../../common" }
tangram_app_layouts = { path = "../../../../../../../../layouts" }
tangram_core = { path = "../../../../../../../../../core" }
tangram_error = { path = "../../../../../../../../../error" }
tangram_id = { path = "../../../../../../../../../id" }
tangram_model = { path = "../../../../../../../../../model" }
tangram_ui = { path = "../../../../../../../../../ui" }
