[package]
edition = "2018"
name = "tangram_app_tuning_client"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
console_error_panic_hook = "0.1"
pinwheel = { path = "../../../../../../../../pinwheel" }
tangram_app_tuning_common = { path = "../common" }
tracing = "0.1"
tracing-wasm = "0.2"
wasm-bindgen = "0.2"
web-sys = "0.3"
