[package]
edition = "2018"
name = "tangram_app_tuning_client"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
console_error_panic_hook = "0.1"
num = "0.4"
serde_json = "1"
tangram_ui = { path = "../../../../../../../../ui" }
tangram_app_tuning_common = { path = "../common" }
wasm-bindgen = "0.2.69"
web-sys = "0.3.45"
