[package]
edition = "2018"
license = "MIT"
name = "libtangram"
version = "0.3.0"

[lib]
crate-type = ["cdylib", "staticlib"]
name = "tangram"
path = "lib.rs"

[dependencies]
libc = "0.2.91"
memmap = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tangram_core = { path = "../../core" }
tangram_error = { path = "../../util/error" }
tangram_model = { path = "../../model" }
