[package]
edition = "2018"
name = "tangram_app_new_model_client"
publish = false
version = "0.0.0"

[[bin]]
name = "tangram_app_new_model_client"
path = "main.rs"

[dependencies]
tangram_ui = { path = "../../../../../../../ui" }
tangram_client = { path = "../../../../../../../client" }
web-sys = "0.3"
