[package]
edition = "2018"
name = "tangram_app_training_stats_column_client"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
console_error_panic_hook = "0.1"
tangram_charts = { path = "../../../../../../../../../../charts" }
wasm-bindgen = "0.2.69"
web-sys = "0.3.45"
