[package]
authors = ["Tangram <root@tangram.dev"]
description = "Tangram makes machine learning easy."
documentation = "https://docs.rs/tangram"
edition = "2018"
homepage = "https://github.com/tangramdotdev/tangram"
license = "MIT"
name = "tangram_table"
publish = true
repository = "https://github.com/tangramdotdev/tangram"
version = "0.6.0"

[lib]
path = "lib.rs"

[dev-dependencies]
insta = "1"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
csv = "1"
fast-float = "0.2"
fnv = "1"
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
tangram_progress_counter = { version = "=0.6.0", path = "../progress_counter" }
tangram_zip = { version = "=0.6.0", path = "../zip" }
