[package]
edition = "2018"
name = "tangram_app_training_grid_item_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
futures = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
pinwheel = "0.1"
sunfish = "0.2"
tangram_app_common = { path = "../../../../../../../../../common" }
tangram_app_layouts = { path = "../../../../../../../../../layouts" }
tangram_app_training_grid_common = { path = "../../../common" }
tangram_charts = { path = "../../../../../../../../../../charts" }
tangram_core = { path = "../../../../../../../../../../core" }
anyhow = { version = "1", features = ["backtrace"] }
tangram_id = { path = "../../../../../../../../../../id" }
tangram_model = { path = "../../../../../../../../../../model" }
tangram_ui = { path = "../../../../../../../../../../ui" }
