[workspace]
members = [
	"crates/*",
	"languages/c",
	"languages/elixir",
	"languages/javascript/node",
	"languages/javascript/wasm",
	"languages/python",
	"languages/python/build",
	"languages/rust",
	"languages/rust/examples/*",
]

[patch.crates-io]
num-bigint-dig = { git = "https://github.com/tangramdotdev/num-bigint", branch = "remove-i128-feature" }
sqlx = { git = "https://github.com/tangramdotdev/sqlx", branch = "libsqlite3-sys-0.23.1" }
sunfish = { git = "https://github.com/tangramdotdev/sunfish" }

[profile.dev.build-override]
debug-assertions = false
opt-level = 3
overflow-checks = false

[profile.release]
lto = true
