[workspace]
members = [
	"cli",
	"languages/c",
	"languages/elixir/native",
	"languages/node/native",
	"languages/python",
	"languages/rust",
	"scripts/crates/*",
	"www",
]

[profile.dev]
opt-level = 1
overflow-checks = false

[profile.release]
lto = true
