[workspace]
resolver = "2"
members = [
	"crates/*",
	"languages/c",
	"languages/elixir",
	"languages/node",
	"languages/python",
	"languages/rust",
	"scripts/crates/*",
]

[profile.dev.build-override]
debug-assertions = false
opt-level = 3
overflow-checks = false

[profile.release]
lto = true
