[workspace]
resolver = "2"
members = [
	"cli",
	"languages/c",
	"languages/elixir/native",
	"languages/node/native",
	"languages/python",
	"languages/rust",
	"scripts/crates/*",
	"www",
]

[profile.dev.build-override]
debug-assertions = false
opt-level = 3
overflow-checks = false

[profile.release]
lto = true
