[package]
edition = "2018"
name = "tangram_www_blog"
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
pinwheel = { path = "../../pinwheel" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tangram_error = { path = "../../error" }
tangram_ui = { path = "../../ui" }
