[package]
edition = "2018"
name = "tangram_www_docs_getting_started_monitor_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
pinwheel = "0.1"
tangram_app_common = { path = "../../../../../../app/common" }
tangram_app_production_stats_column_server = { path = "../../../../../../app/pages/repos/_/models/_/production_stats/columns/_/server"}
tangram_app_production_stats_index_server = { path = "../../../../../../app/pages/repos/_/models/_/production_stats/index/server"}
tangram_app_ui = { path = "../../../../../../app/ui" }
tangram_charts = { path = "../../../../../../charts" }
sunfish = "0.2"
tangram_ui = { path = "../../../../../../ui" }
tangram_www_layouts = { path = "../../../../../layouts" }
tangram_www_ui = { path = "../../../../../ui" }
