[package]
edition = "2018"
license = "MIT"
name = "tangram_script_generate_license"
version = "0.0.0"

[[bin]]
name = "tangram_script_generate_license"
path = "main.rs"

[dependencies]
base64 = "0.13"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "3.0.0-beta.2", features = ["color"] }
rand = "0.8"
rsa = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.9"
tangram_error = { path = "../../../util/error" }
tangram_id = { path = "../../../util/id" }
