[package]
edition = "2018"
license = "MIT"
name = "tangram_script_build_word_embedding_models"
version = "0.0.0"

[[bin]]
name = "tangram_script_build_word_embedding_models"
path = "main.rs"

[build-dependencies]
cc = "1"

[dependencies]
duct = "0.13"
ndarray = { version = "0.15", features = ["rayon"] }
ndarray-npy = "0.8"
num = "0.4"
rand = "0.8"
rayon = "1.5"
rmp-serde = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tangram_error = { path = "../../../util/error" }
tangram_model = { path = "../../../model" }
tangram_serialize = { path = "../../../util/serialize" }
