[package]
edition = "2018"
license = "MIT"
name = "tangram_script_track_test"
version = "0.0.0"

[[bin]]
name = "tangram_scripts"
path = "main.rs"

[dependencies]
base64 = "0.13"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = { version = "0.5", features = ["serde"] }
clap = { version = "3.0.0-beta.2", features = ["color"] }
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
rand = "0.8"
rayon = "1.5"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.9"
tangram_app_common = { path = "../../../app/common" }
tangram_error = { path = "../../../util/error" }
tangram_id = { path = "../../../util/id" }
tangram_model = { path = "../../../model" }
tangram_serialize = { path = "../../../util/serialize" }
tangram_table = { path = "../../../table" }
url = "2"
