[package]
edition = "2018"
name = "tangram_app_tuning_client"
publish = false
version = "0.0.0"

[[bin]]
name = "tangram_app_tuning_client"
path = "main.rs"

[dependencies]
pinwheel = "0.1"
tangram_app_tuning_common = { path = "../common" }
tangram_client = { path = "../../../../../../../../client" }
web-sys = "0.3"
