[package]
authors = ["Tangram <root@tangram.xyz"]
description = "Tangram is an all-in-one automated machine learning framework."
documentation = "https://docs.rs/tangram"
edition = "2018"
homepage = "https://github.com/tangramxyz/tangram"
license = "MIT"
name = "tangram_finite"
publish = true
repository = "https://github.com/tangramxyz/tangram"
version = "0.5.0"

[lib]
path = "lib.rs"

[dependencies]
num = "0.4"
serde= { version = "1", features = ["derive"] }
