[package]
authors = ["Tangram <root@tangram.dev"]
description = "Tangram makes machine learning easy."
documentation = "https://docs.rs/tangram"
edition = "2018"
homepage = "https://github.com/tangramdotdev/tangram"
license = "MIT"
name = "tangram_finite"
publish = true
repository = "https://github.com/tangramdotdev/tangram"
version = "0.6.0"

[lib]
path = "lib.rs"

[dependencies]
num = "0.4"
serde= { version = "1", features = ["derive"] }
