[package]
edition = "2018"
name = "tangram_app_training_metrics_roc_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
futures = "0.3"
pinwheel = "0.1"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
num = "0.4"
tangram_app_common = { path = "../../../../../../../../common" }
tangram_app_layouts = { path = "../../../../../../../../layouts" }
tangram_charts = { path = "../../../../../../../../../charts" }
tangram_core = { path = "../../../../../../../../../core" }
tangram_error = { path = "../../../../../../../../../error" }
tangram_finite = { path = "../../../../../../../../../finite" }
tangram_id = { path = "../../../../../../../../../id" }
tangram_model = { path = "../../../../../../../../../model" }
sunfish = { path = "../../../../../../../../../sunfish" }
tangram_ui = { path = "../../../../../../../../../ui" }
