[package]
edition = "2018"
name = "tangram_www_blog_index_server"
version = "0.0.0"

[lib]
path = "page.rs"

[dependencies]
pinwheel = { path = "../../../../../pinwheel" }
tangram_ui = { path = "../../../../../ui" }
tangram_www_content = { path = "../../../../content" }
tangram_www_layouts = { path = "../../../../layouts" }
