[package]
edition = "2018"
name = "tangram_node"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
name = "tangram_node"
path = "lib.rs"

[dependencies]
node_api = { version = "0.3", features = ["serde_1"] }
memmap = "0.7"
serde = { version = "1", features = ["derive"] }
tangram_core = { path = "../../crates/core" }
anyhow = { version = "1", features = ["backtrace"] }
tangram_model = { path = "../../crates/model" }
