[package]
authors = ["Tangram <root@tangram.xyz"]
description = "Tangram is an automated machine learning framework designed for programmers."
documentation = "https://docs.rs/tangram"
edition = "2018"
homepage = "https://github.com/tangramxyz/tangram"
license = "MIT"
name = "tangram_progress_counter"
publish = true
repository = "https://github.com/tangramxyz/tangram"
version = "0.4.0"

[lib]
path = "lib.rs"

[dev-dependencies]
rayon = "1.5"
