[package]
authors = ["Tangram <root@tangram.dev"]
description = "Tangram is an all-in-one automated machine learning framework."
documentation = "https://docs.rs/tangram"
edition = "2018"
homepage = "https://github.com/tangramdotdev/tangram"
license = "MIT"
name = "tangram_progress_counter"
publish = true
repository = "https://github.com/tangramdotdev/tangram"
version = "0.6.0"

[lib]
path = "lib.rs"

[dev-dependencies]
rayon = "1.5"
