[package]
authors = ["Tangram <root@tangram.xyz"]
description = "Make predictions with a Tangram model from your Rust app. Learn more at https://www.tangram.xyz/."
documentation = "https://docs.rs/tangram"
edition = "2018"
homepage = "https://github.com/tangramxyz/tangram"
license = "MIT"
name = "tangram_macro"
publish = true
repository = "https://github.com/tangramxyz/tangram"
version = "0.4.0"

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
