[package]
edition = "2018"
name = "tangram_www_docs_train_configuration_server"
publish = false
version = "0.0.0"

[lib]
path = "page.rs"

[dependencies]
pinwheel = { path = "../../../../../../pinwheel" }
syn = "1.0"
tangram_www_ui = { path = "../../../../../ui" }
tangram_www_layouts = { path = "../../../../../layouts" }
tangram_serve = { path = "../../../../../../serve" }
tangram_ui = { path = "../../../../../../ui" }
