[package]
edition = "2018"
license = "MIT"
name = "tangram_distribute_native_extensions"
publish = false
version = "0.0.0"

[[bin]]
name = "tangram_distribute_native_extensions"
path = "main.rs"

[dependencies]
tangram_build = { path = "../build" }
tangram_error = { path = "../error" }
