[package]
edition = "2018"
name = "tangram_app_training_metrics_index_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
futures = "0.3"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
num = "0.4"
pinwheel = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.7"
sunfish = "0.2"
tangram_app_common = { path = "../../../../../../../../common" }
tangram_app_layouts = { path = "../../../../../../../../layouts" }
tangram_app_ui = { path = "../../../../../../../../ui" }
tangram_core = { path = "../../../../../../../../../core" }
anyhow = { version = "1", features = ["backtrace"] }
tangram_id = { path = "../../../../../../../../../id" }
tangram_model = { path = "../../../../../../../../../model" }
tangram_ui = { path = "../../../../../../../../../ui" }
tangram_zip = { path = "../../../../../../../../../zip" }
