[package]
edition = "2018"
name = "tangram_www_docs_monitor_client"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
console_error_panic_hook = "0.1"
tangram_charts = { path = "../../../../../../charts" }
tangram_ui = { path = "../../../../../../ui" }
wasm-bindgen = "0.2"
web-sys = "0.3"
