[package]
edition = "2018"
name = "tangram_www_index_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
pinwheel = "0.1"
futures = "0.3"
tangram_charts = { path = "../../../../charts" }
sunfish = { path = "../../../../sunfish" }
tangram_ui = { path = "../../../../ui" }
tangram_finite = { path = "../../../../finite" }
tangram_www_ui = { path = "../../../ui" }
tangram_www_index_common = { path = "../common" }
tangram_www_layouts = { path = "../../../layouts" }
