[package]
edition = "2018"
name = "tangram_app_training_stats_column_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
futures = "0.3"
pinwheel = "0.2"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_urlencoded = "0.7"
num = "0.4"
tangram_app_common = { path = "../../../../../../../../../common" }
tangram_app_ui = { path = "../../../../../../../../../ui" }
tangram_app_layouts = { path = "../../../../../../../../../layouts" }
tangram_charts = { path = "../../../../../../../../../../charts" }
tangram_core = { path = "../../../../../../../../../../core" }
anyhow = { version = "1", features = ["backtrace"] }
tangram_id = { path = "../../../../../../../../../../id" }
tangram_model = { path = "../../../../../../../../../../model" }
sunfish = "0.2"
tangram_ui = { path = "../../../../../../../../../../ui" }
