[package]
edition = "2018"
name = "tangram_app_training_stats_column_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
futures = "0.3"
pinwheel = { path = "../../../../../../../../../../pinwheel" }
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_urlencoded = "0.7"
num = "0.4"
tangram_app_common = { path = "../../../../../../../../../common" }
tangram_app_ui = { path = "../../../../../../../../../ui" }
tangram_app_layouts = { path = "../../../../../../../../../layouts" }
tangram_charts = { path = "../../../../../../../../../../charts" }
tangram_core = { path = "../../../../../../../../../../core" }
tangram_error = { path = "../../../../../../../../../../error" }
tangram_id = { path = "../../../../../../../../../../id" }
tangram_model = { path = "../../../../../../../../../../model" }
tangram_serve = { path = "../../../../../../../../../../serve" }
tangram_ui = { path = "../../../../../../../../../../ui" }
