[package]
edition = "2018"
license = "MIT"
name = "erl_nif_macro"
publish = true
version = "0.0.0"

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full"] }
tangram_zip = { path = "../../zip" }
