[package]
edition = "2018"
license = "MIT"
name = "tangram_script_distribute_native_extensions"
publish = false
version = "0.0.0"

[[bin]]
name = "tangram_script_distribute_native_extensions"
path = "main.rs"

[dependencies]
tangram_error = { path = "../../../crates/error" }
tangram_script_build = { path = "../build" }
