[package]
edition = "2018"
name = "tangram_app_model_edit_server"
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = { version = "0.5", features = ["serde"] }
html = { path = "../../../../../../../../util/html" }
http = "0.2"
hyper = { version = "0.14", features = ["server"] }
num = "0.4"
serde = { version = "1", features = ["derive"] }
serde_urlencoded = "0.7"
serde_json = "1"
sqlx = { version = "0.5", default-features = false, features = ["any", "chrono", "postgres", "runtime-tokio-rustls", "sqlite"] }
tangram_app_common = { path = "../../../../../../../common" }
tangram_app_layouts = { path = "../../../../../../../layouts" }
tangram_core = { path = "../../../../../../../../core" }
tangram_error = { path = "../../../../../../../../util/error" }
tangram_id = { path = "../../../../../../../../util/id" }
tangram_model = { path = "../../../../../../../../model" }
tangram_serve = { path = "../../../../../../../../util/serve" }
tangram_ui = { path = "../../../../../../../../ui" }
