[package]
edition = "2018"
name = "tangram_app_production_class_metrics_client"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
console_error_panic_hook = "0.1"
pinwheel = { path = "../../../../../../../../../pinwheel" }
tangram_charts = { path = "../../../../../../../../../charts" }
tangram_ui = { path = "../../../../../../../../../ui" }
wasm-bindgen = "0.2"
