[package]
edition = "2018"
name = "tangram_app_production_class_metrics_client"
publish = false
version = "0.0.0"

[[bin]]
name = "tangram_app_production_class_metrics_client"
path = "main.rs"

[dependencies]
pinwheel = "0.1"
tangram_charts = { path = "../../../../../../../../../charts" }
tangram_client = { path = "../../../../../../../../../client" }
tangram_ui = { path = "../../../../../../../../../ui" }
