[package]
edition = "2018"
name = "tangram_app_login_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
pinwheel = "0.2"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
lettre = { version = "0.10.0-rc.2", default-features = false, features = ["builder", "hostname", "smtp-transport", "tokio1-rustls-tls"] }
rand = "0.8"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_urlencoded = "0.7"
sunfish = "0.2"
sqlx = { version = "0.5", default-features = false, features = ["any", "chrono", "postgres", "runtime-tokio-rustls", "sqlite"] }
tangram_app_common = { path = "../../../common" }
tangram_app_layouts = { path = "../../../layouts" }
anyhow = { version = "1", features = ["backtrace"] }
tangram_id = { path = "../../../../id" }
tangram_ui = { path = "../../../../ui" }
url = { version = "2", features = ["serde"] }
