[package]
edition = "2018"
name = "tangram_www_docs_index_server"
publish = false
version = "0.0.0"

[lib]
path = "page.rs"

[dependencies]
pinwheel = { path = "../../../../../pinwheel" }
tangram_app_common = { path = "../../../../../app/common" }
tangram_www_ui = { path = "../../../../ui" }
tangram_www_layouts = { path = "../../../../layouts" }
tangram_serve = { path = "../../../../../serve" }
tangram_ui = { path = "../../../../../ui" }
