[package]
edition = "2018"
name = "tangram_www_docs_index_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
pinwheel = "0.1"
tangram_app_common = { path = "../../../../../app/common" }
tangram_www_ui = { path = "../../../../ui" }
tangram_www_layouts = { path = "../../../../layouts" }
sunfish = { path = "../../../../../sunfish" }
tangram_ui = { path = "../../../../../ui" }
