[package]
edition = "2018"
name = "tangram_app_tuning_common"
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
html = { path = "../../../../../../../../util/html" }
serde = { version = "1", features = ["derive"] }
