[package]
edition = "2018"
license = "MIT"
name = "tangram_script_build_pkgs"
version = "0.0.0"

[[bin]]
name = "tangram_script_build_pkgs"
path = "main.rs"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "3.0.0-beta.2", features = ["color"] }
digest = "0.9"
dirs = "3"
duct = "0.13"
env_logger = "0.8"
flate2 = "1"
hex = "0.4"
indoc = "1"
log = "0.4"
md-5 = "0.9"
rayon = "1.5"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha-1 = "0.9"
sha2 = "0.9"
tangram_error = { path = "../../../util/error" }
tangram_script_build = { path = "../build" }
tar = "0.4"
url = "2"
which = "4"
