[package]
authors = ["Tangram <root@tangram.xyz"]
description = "Tangram is an automated machine learning framework designed for programmers."
documentation = "https://docs.rs/tangram"
edition = "2018"
homepage = "https://github.com/tangramxyz/tangram"
license = "MIT"
name = "tangram_model"
publish = true
repository = "https://github.com/tangramxyz/tangram"
version = "0.4.0"

[lib]
path = "lib.rs"

[dependencies]
anyhow = { version = "1", features = ["backtrace"] }
buffalo = "0.1"
fnv = "1"
num = "0.4"
tangram_linear = { version = "0.4", path = "../linear" }
tangram_text = { version = "0.4", path = "../text" }
tangram_tree = { version = "0.4", path = "../tree" }
