[package]
edition = "2018"
license = "MIT"
name = "tangram_model"
publish = true
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
buffalo = { path = "../buffalo" }
fnv = "1"
num = "0.4"
tangram_error = { path = "../error" }
tangram_linear = { path = "../linear" }
tangram_text = { path = "../text" }
tangram_tree = { path = "../tree" }
