[package]
authors = ["Tangram <root@tangram.xyz"]
description = "Tangram is an automated machine learning framework designed for programmers."
documentation = "https://docs.rs/tangram"
edition = "2018"
homepage = "https://github.com/tangramxyz/tangram"
license = "MIT"
name = "tangram_core"
publish = true
repository = "https://github.com/tangramxyz/tangram"
version = "0.4.0"

[lib]
path = "lib.rs"

[dependencies]
bitvec = "0.19"
buffalo = "0.1"
chrono = { version = "0.4", features = ["serde"] }
fast-float = "0.2"
fnv = "1"
indexmap = { version = "1.6", features = ["serde-1"] }
itertools = "0.10"
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
rand = "0.8"
rand_xoshiro = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = { version = "1", features = ["backtrace"] }
tangram_features = { path = "../features" }
tangram_finite = { path = "../finite" }
tangram_id = { path = "../id" }
tangram_kill_chip = { path = "../kill_chip" }
tangram_linear = { path = "../linear" }
tangram_metrics = { path = "../metrics" }
tangram_model = { path = "../model" }
tangram_progress_counter = { path = "../progress_counter" }
tangram_table = { path = "../table" }
tangram_text = { path = "../text" }
tangram_tree = { path = "../tree" }
tangram_zip = { path = "../zip" }
