[package]
edition = "2018"
name = "tangram_www_pricing_server"
version = "0.0.0"

[lib]
path = "page.rs"

[dependencies]
pinwheel = { path = "../../../../pinwheel" }
tangram_www_layouts = { path = "../../../layouts" }
tangram_ui = { path = "../../../../ui" }
