[package]
edition = "2018"
name = "tangram_www_docs_getting_started_predict_node_server"
publish = false
version = "0.0.0"

[lib]
path = "page.rs"

[dependencies]
html = { path = "../../../../../../../html" }
indoc = "1"
tangram_www_common = { path = "../../../../../../common" }
tangram_www_layouts = { path = "../../../../../../layouts" }
tangram_serve = { path = "../../../../../../../serve" }
tangram_ui = { path = "../../../../../../../ui" }
