[package]
edition = "2018"
name = "tangram_app_new_model_server"
publish = false
version = "0.0.0"

[lib]
path = "lib.rs"

[dependencies]
futures = "0.3"
pinwheel = "0.1"
http = "0.2"
hyper = { version = "0.14", features = ["full"] }
multer = "2"
num = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tangram_app_common = { path = "../../../../../../common" }
tangram_app_ui = { path = "../../../../../../ui" }
tangram_app_layouts = { path = "../../../../../../layouts" }
tangram_core = { path = "../../../../../../../core" }
tangram_error = { path = "../../../../../../../error" }
tangram_id = { path = "../../../../../../../id" }
tangram_model = { path = "../../../../../../../model" }
sunfish = { path = "../../../../../../../sunfish" }
tangram_ui = { path = "../../../../../../../ui" }
