[package]
edition = "2018"
name = "tangram_elixir"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
name = "tangram_elixir"
path = "lib.rs"

[dependencies]
erl_nif = { path = "../../../crates/erl_nif", features = ["serde_1"] }
memmap = "0.7"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
tangram_core = { path = "../../../crates/core" }
tangram_error = { path = "../../../crates/error" }
tangram_model = { path = "../../../crates/model" }
