[package]
edition = "2018"
license = "MIT"
name = "tangram"
publish = true
readme = "README.md"
version = "0.3.0"

[lib]
path = "lib.rs"

[features]
default = []
tokio_1 = ["tokio"]

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
memmap = "0.7"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tangram_core = { path = "../../crates/core" }
tangram_error = { path = "../../crates/error" }
tangram_macro = { path = "macro" }
tangram_model = { path = "../../crates/model" }
tokio = { version = "1", features = [], optional = true }
url = { version = "2", features = ["serde"] }
