[package]
edition = "2018"
name = "tangram_app_model_index_client"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
console_error_panic_hook = "0.1"
tangram_charts = { path = "../../../../../../../../charts" }
wasm-bindgen = "0.2.69"
