[package]
edition = "2018"
name = "tangram_node"
publish = false
version = "0.0.0"

[lib]
crate-type = ["cdylib"]
name = "tangram_node"
path = "lib.rs"

[dependencies]
node_api = { path = "../../../crates/node_api", features = ["serde_1"] }
memmap = "0.7"
serde = { version = "1", features = ["derive"] }
tangram_core = { path = "../../../crates/core" }
tangram_error = { path = "../../../crates/error" }
tangram_model = { path = "../../../crates/model" }
