[package]
description = "Tangram makes it easy for programmers to train, deploy, and monitor machine learning models."
documentation = "https://docs.rs/tangram"
edition = "2021"
homepage = "https://github.com/tangramdotdev/tangram"
license = "MIT"
name = "tangram_id"
publish = true
repository = "https://github.com/tangramdotdev/tangram"
rust-version = "1.56"
version = "0.7.0"

[lib]
path = "lib.rs"

[dependencies]
rand = "0.8"
serde = { version = "1", features = ["derive"] }
