[package]
edition = "2018"
license = "MIT"
name = "tangram_metrics"
version = "0.0.0"

[lib]
path = "lib.rs"

[dev-dependencies]
insta = "1"

[dependencies]
itertools = "0.10"
ndarray = { version = "0.15", features = ["rayon"] }
num = "0.4"
tangram_zip = { path = "../util/zip" }
